### ISSUE TITLE
Kernel infinite refresh loop.

### ISSUE THREAD

**Issue by Coop0801** [0xNODES/community#38]
Multiple browsers chrome, edge & Firefox (multiple desktops + mobile, also tried on different WIFI)
Metamask + Trust wallet (both the latest version)
Constant refreshing of the KERNEL once the wallet is connected. Site loads OK when I do not connect a wallet. Its like someone is hitting F5 every second leaving the kernel unusable (I have BIOS actively staked)  . (I have uploaded a video showing the issue in the discord channel "kernel-issues". Console log shown below.

![unknown (1)](https://user-images.githubusercontent.com/97392895/148684711-af0695a3-a20d-46a9-9211-cc1c9a606caa.png)

**Comment by tomxnodes** [comment]
resolved
!

**Comment by jensonb** [comment]
@Coop0801 I think this issue should be resolved by now, are you still experiencing this issue? Thanks!

**Comment by Coop0801** [comment]
Issue has still not been resolved, still unable to access the kernel.
